#search all vaccines and manufactory in VO_inferred
select distinct ?class ?label ?factory
where {
  	?class rdfs:label ?label .
#  ?class rdfs:subClassOf* ?o .
#  ?o owl:onProperty <http://purl.obolibrary.org/obo/VO_0001243>; owl:someValuesFrom <http://purl.obolibrary.org/obo/NCBITaxon_9606> .
    ?class rdfs:subClassOf* ?o1 .
    ?o1 owl:onProperty <http://purl.obolibrary.org/obo/OBI_0000304>; owl:hasValue ?factory_ID .
    ?factory_ID rdfs:label ?factory .
}