#search all human vaccines in VO_inferred
select distinct ?class ?label
where {
  	?class rdfs:label ?label .
	?class rdfs:subClassOf ?o .
    ?o owl:onProperty <http://purl.obolibrary.org/obo/VO_0001243>; owl:someValuesFrom <http://purl.obolibrary.org/obo/NCBITaxon_9606> .
}

# search all subclass of those human vaccines VO_2.2

select distinct ?class ?label ?sub ?sub_label
where {
  	?class rdfs:label ?label .
	?class rdfs:subClassOf ?o .
    ?o owl:onProperty <http://purl.obolibrary.org/obo/VO_0001243>; owl:someValuesFrom <http://purl.obolibrary.org/obo/NCBITaxon_9606> .
	?sub rdfs:subClassOf* ?class .
	?sub rdfs:label ?sub_label .
}


# union 2, and 2.2

select * {
	?class rdfs:label ?label .
    { 
		select ?class 
			where { 
					?class rdfs:subClassOf ?o .
  					?o owl:onProperty <http://purl.obolibrary.org/obo/VO_0001243>; owl:someValuesFrom <http://purl.obolibrary.org/obo/NCBITaxon_9606> .
            } 
       } UNION {
         select ?class 
         where {
					?class rdfs:subClassOf* ?mom .					
					?mom rdfs:subClassOf ?o .
  					?o owl:onProperty <http://purl.obolibrary.org/obo/VO_0001243>; owl:someValuesFrom <http://purl.obolibrary.org/obo/NCBITaxon_9606> .
                    
					}
}
}